Revert "Bump gocloud.dev from 0.32.0 to 0.33.0 (#282)"
This reverts commit 5145eb5411c187b613f1d30b51e9047a2a9593fa.

A downstream build of this repository uses Bazel and it appears that this version bump introduces a newer version of aws sdk that doesn't currently play well with Gazelle-generated build files.

We should do a proper investigation of this, but in the meantime let's revert. I poked a but and I wasn't able to find an obvious way to fix.

As far as I can tell, `github.com/aws/aws-sdk-go-v2 v1.19.0 => v1.20.0` and its transitive dependencies introduces this issue.

```
ERROR: /private/var/tmp/_bazel_srhodes/369bcf7075217f4affd072aeac1cf7cb/external/com_github_aws_aws_sdk_go_v2_service_s3/BUILD.bazel:3:11: no such target '@com_github_aws_aws_sdk_go_v2_internal_endpoints_v2//:awsrulesfn': target 'awsrulesfn' not declared in package '' defined by /private/var/tmp/_bazel_srhodes/369bcf7075217f4affd072aeac1cf7cb/external/com_github_aws_aws_sdk_go_v2_internal_endpoints_v2/BUILD.bazel (Tip: use `query "@com_github_aws_aws_sdk_go_v2_internal_endpoints_v2//:*"` to see all the targets in that package) and referenced by '@com_github_aws_aws_sdk_go_v2_service_s3//:s3'
ERROR: Analysis of target '//cmd/sansshell-server:sansshell-server' failed; build aborted:
```